# -*- coding: utf-8 -*-
"""Preprocess html tags.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15fezyY_ic9cVg8XSvEB0VOvR-3urwu9D

# **` fast HTML parser in Python`**

***Some examples on how to use selectolax***
"""

#https://github.com/rushter/selectolax/tree/master/examples
#https://rushter.com/blog/python-fast-html-parser/

"""***Installation of selectolax module***"""

!pip install selectolax

"""***Imoport Libraries***"""

from time import time

#import warc
from bs4 import BeautifulSoup
from selectolax.parser import HTMLParser

"""***Create function tha clean html file using BeautifulSoup***"""

def get_text_bs(html):
    tree = BeautifulSoup(html, 'lxml')

    body = tree.body
    if body is None:
        return None

    for tag in body.select('script'):
        tag.decompose()
    for tag in body.select('style'):
        tag.decompose()

    text = body.get_text(separator='\n')
    return text

"""***Save the Output of function in text file***"""

fil = open('text.html','r')
html = fil.read()
output1 = get_text_bs(html)
wr1 = open('output1.txt','w')
wr1.write(output1)
wr1.close()

"""***Create function tha clean html file using BeautifulSoup***"""

def get_text_selectolax(html):
    tree = HTMLParser(html)

    if tree.body is None:
        return None

    for tag in tree.css('script'):
        tag.decompose()
    for tag in tree.css('style'):
        tag.decompose()

    text = tree.body.text(separator='\n')
    return text

"""***Save the Output of function in text file***"""

output2 = get_text_selectolax(html)
wr2 = open('output2.txt','w')
wr2.write(output2)
wr2.close()

"""***Remove empty lines***"""

with open('output1.txt', 'r+') as fd:
    lines = fd.readlines()
    fd.seek(0)
    fd.writelines(line for line in lines if line.strip())
    fd.truncate()

with open('output2.txt', 'r+') as fd:
    lines = fd.readlines()
    fd.seek(0)
    fd.writelines(line for line in lines if line.strip())
    fd.truncate()